# Generated by Django 3.0.7 on 2021-04-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
